"""set device, navigaton to unique=False in Login model migration

Revision ID: 0694a88c22d4
Revises: a077c3798828
Create Date: 2023-10-20 12:33:09.619445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0694a88c22d4'
down_revision: Union[str, None] = 'a077c3798828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('logins_device_key', 'logins', type_='unique')
    op.drop_constraint('logins_navigator_key', 'logins', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('logins_navigator_key', 'logins', ['navigator'])
    op.create_unique_constraint('logins_device_key', 'logins', ['device'])
    # ### end Alembic commands ###
