"""set navigator unique in Inscription model to False migration

Revision ID: 12268cff2721
Revises: 5dd420a7e924
Create Date: 2023-10-19 22:44:10.055712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12268cff2721'
down_revision: Union[str, None] = '5dd420a7e924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('inscriptions_navigator_key', 'inscriptions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('inscriptions_navigator_key', 'inscriptions', ['navigator'])
    # ### end Alembic commands ###
