"""Adding column - assigned_language to user's model

Revision ID: 13d0fbfb452d
Revises: c7fefc267662
Create Date: 2024-01-16 21:27:07.596435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13d0fbfb452d'
down_revision: Union[str, None] = 'c7fefc267662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('assigned_language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'assigned_language')
    # ### end Alembic commands ###
