"""the last good one version with OriginAudio model included and category property added to origin model migration

Revision ID: 3f48d6020622
Revises: b2129123c99e
Create Date: 2023-11-16 11:20:58.409559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f48d6020622'
down_revision: Union[str, None] = 'b2129123c99e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('origin_audios', 'status')
    op.drop_column('origin_audios', 'text')
    op.drop_column('origin_audios', 'language')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('origin_audios', sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('origin_audios', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('origin_audios', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
