"""set device unique in Inscription model to False migration

Revision ID: 5dd420a7e924
Revises: d9611641305d
Create Date: 2023-10-19 22:38:16.550307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dd420a7e924'
down_revision: Union[str, None] = 'd9611641305d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('inscriptions_device_key', 'inscriptions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('inscriptions_device_key', 'inscriptions', ['device'])
    # ### end Alembic commands ###
