"""the version with OriginAudio model included and category property added to origin model migration

Revision ID: b2129123c99e
Revises: 0694a88c22d4
Create Date: 2023-11-16 11:11:54.817825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b2129123c99e'
down_revision: Union[str, None] = '0694a88c22d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('origin_audios',
                    sa.Column('audio', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column(
                        'text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('status', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('origin_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['origin_id'], ['origins.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('origins', sa.Column('category', sa.String(), nullable=True))
    op.drop_column('origins', 'audio')
    op.alter_column('translations', 'audio',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('translations', 'audio',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.add_column('origins', sa.Column('audio', sa.VARCHAR(),
                  autoincrement=False, nullable=False))
    op.drop_column('origins', 'category')
    op.drop_table('origin_audios')
    # ### end Alembic commands ###
